services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run build

  server:
    build:
      context: ./server
    environment:
      REDIS_URL: "redis://redis:6379"
    volumes:
      - ./server:/app         
      - /app/node_modules     
    command: npm run start
    depends_on:
      - db
      - redis  
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html:ro
    depends_on:
      - client
      - server
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge