services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=deepsearchdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend API Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
      - NODE_ENV=prod
      - PROD_DB_URL=postgresql://postgres:admin@postgres:5432/deepsearchdb
    networks:
      - app-network
    depends_on:
      - postgres

  # Frontend React Application
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    environment:
      - NODE_OPTIONS="--max-old-space-size=8192"
      - VITE_APP_API_URL=https://backend:3000
    networks:
      - app-network
    depends_on:
      - server

  # Nginx Reverse Proxy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    depends_on:
      - client
      - server

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: